### ISSUE TITLE
Utilizing CraftTweaker Syntax causes a crash.

### ISSUE THREAD

**Issue by Boolyman** [Magneticraft-Team/Magneticraft#113]
Even simply copy and pasting the example script from the Magneticraft wiki causes the following crash.

https://pastebin.com/9mDjPL35

**Comment by cout970** [comment]
Thanks for the report, you just need to include mtlib: https://minecraft.curseforge.com/projects/mtlib
I will update the wiki and add the library as 'optional library' in curseforge
