### ISSUE TITLE
Missing block - V.2.4.0

### ISSUE THREAD

**Issue by Darkness1744** [Magneticraft-Team/Magneticraft#115]
i was building an hydraulic press but i found out a block was missing: Support column (Z axis)
![mag 1](https://user-images.githubusercontent.com/40572654/41859061-9c58a0c6-789b-11e8-9a78-d6eab1ed3292.PNG)

**Comment by calloatti** [comment]
You can place the support column vertically or horizontally.

**Comment by Darkness1744** [comment]
i tryed but it diden´t work.

**Comment by cout970** [comment]
I will remove that requirement, it's just annoying to place the column block in the right direction

**Comment by cout970** [comment]
The version 2.4.1 removed the need for custom orientation on multiblock structures
