### ISSUE TITLE
Oil Refinery should use steam

### ISSUE THREAD

**Issue by WrongWeekend** [Magneticraft-Team/Magneticraft#118]
Based on this diagram:

https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Refine.svg/512px-Refine.svg.png

It would be more realistic to have the oil heater run on heat energy rather than electricity, and the refinery use piped-in steam instead of electricity. The latter change would also give a use to boilers and steam even after steam-powered electricity generation is obsolete.

**Comment by cout970** [comment]
The oil heater already runs on heat, and the refinery uses hot crude which is basically 'oil steam'. I have to say that I'm not a fan of using electricity in the refinery, but steam makes no sense, the oil is heated about 400 º C and the steam cannot be heated more than 100ºC in a boiler, we would need another machine to heat up steam and I don't think it's worth

**Comment by WrongWeekend** [comment]
I stand corrected on the oil heater.

As for the refinery, steam is not used to heat the oil further (so regular steam from Magneticraft's already existing boiler or oil heater would realistically work) but it is a key part of separating the hot crude oil into separate layers. Basically, the steam (being water) cannot mix with the oil, but its injection causes each substance within the hot crude to vaporize at their own individual vaporization temperatures. So lighter fluids such as gasoline, diesel, kerosene, etc. evaporate individually and condense at higher levels of the distillation tower, leaving the heavy oil residue at the bottom.

These explain it more in-depth:
https://www.e-education.psu.edu/fsc432/content/atmospheric-and-vacuum-distillation-units
http://folk.ntnu.no/skoge/publications/1999/DistillationTheory/original/distillationtheory.pdf

The heavy oil residue (currently in the mod but without any uses) is refined through vacuum distillation, which still requires and can operate entirely on steam, but more recently vacuumn pumps are used (which could run on electricity) to pump out and maintain a vacuum inside a (differently constructed) distillation chamber.
