### ISSUE TITLE
Has the Alternator to Convert RF To Volts Been Removed?

### ISSUE THREAD

**Issue by Boolyman** [Magneticraft-Team/Magneticraft#120]
I am scratching my head trying to find a way to convert RF into V for magneticraft, but everything I read is referencing blocks I don't actually see in JEI.  Is there no longer a way to convert RF into Volts?  That would really suck.

**Comment by cout970** [comment]
To Convert RF into magneticraft electricty you can use en RF heater, a steam boiler and a steam engine.
Currently there is ~bug~ _feature_ that let's you charge and discharge RF items in a Battery block.

Also there is a bug that make the items in the mod not appear in JEI. I have to fix it but I'm too busy this weeks, in 2-3 weeks I will have time again to fix all the current issues.

**Comment by Boolyman** [comment]
Thanks for the response.  Though I just realized that the multiblocks don't have animations?  Man, thats killin me.  I may still use it in my upcoming pack for the early game sluice box stuff... but damn, I was really looking forward to taking players through some cool multiblocks as well.

**Comment by cout970** [comment]
Sorry, but the multiblocks don't have animations for several reasons: 
-  Making animations in code is hard, unmaintainable and breaks if you change the model in the future
- To create animations we need a Editor for them ([we already did that](https://github.com/cout970/Modeler))
- We need to implement a Exporter to a standard format that supports animations (In the works)
- We need to implement a Loader and an Animator to use the animations in the game (missing)

This may seem simple but I been working for almost a year on this. The problems is that I have little time to advance and I have to split that time between adding features to the mod and working on animations.

With that in mind, I think in a month animations will be done, and the development will speed up quite a bit.

**Comment by Boolyman** [comment]
Well, the pack isnt coming out for probably 3 or so months.  So I will check back.  Thanks!  And I love the mod otherwise!

**Comment by cout970** [comment]
Added in the last release
