### ISSUE TITLE
Can the solar tower be turned off?

### ISSUE THREAD

**Issue by duncanwebb** [Magneticraft-Team/Magneticraft#127]
The solar tower turn to lava if it has been running for a while, even after it has been unformed by attacking it with a pick.

I would like to turn it off with a redstone signal (a lever in front of the blueprint block didn’t work) when it is off the solar mirrors go flat.

**Comment by cout970** [comment]
You can't turn off the solar tower, that's one of it's mechanics, you need to make sure that stays cold by using or dissipating the excess energy. 
In the other hand the tower shouldn't melt down when it's not formed, I will have to fix that.

**Comment by duncanwebb** [comment]
Using it is no problem however using it continuously is a problem and was hoping that the mirrors could be disconnected. I cannot see what mechanics you can use to dissipate the heat except the thermopile (too early in my game for steel). I can't find any use for batteries.

The book says it needs 7 corrugate (should be corrugated) iron machine blocks but it needs 8. The mirrors need two corrugated iron machine blocks instead of 19 iron grate machine blocks.

I'm have a lot of fun using the mod, many thanks.
