### ISSUE TITLE
Issue with Changing grinder recipe with crafttweaker

### ISSUE THREAD

**Issue by avidgamer5918** [Magneticraft-Team/Magneticraft#128]
this is the script i wrote
mods.magneticraft.Grinder.removeRecipe(<minecraft:log>);
mods.magneticraft.Grinder.addRecipe(<minecraft:log>,<minecraft:planks>(6), 0.0, 100, true);

this is what i get when i open a world
Error executing {[0:crafttweaker]: Magneticraft.zs}: Not supported yet.
 just wondering if this works yet or if i did something wrong with the script

**Comment by cout970** [comment]
I'm not an expert in zen script but those lines seem wrong, try:
```
mods.magneticraft.Grinder.removeRecipe(<minecraft:log>);
mods.magneticraft.Grinder.addRecipe(<minecraft:log>,<minecraft:planks:6>, <minecraft:planks>, 0.0, 100, true);
```

**Comment by cout970** [comment]
Also I think you can use and empty second output with:
```
mods.magneticraft.Grinder.addRecipe(<minecraft:log>, <minecraft:planks:6>, <minecraft:air>, 0.0, 100, true);
```

**Comment by avidgamer5918** [comment]
i figured it out thank you
