### ISSUE TITLE
Sluice Box Ticking Entity

### ISSUE THREAD

**Issue by IdrisQe** [Magneticraft-Team/Magneticraft#131]
I am unsure why this is happening when the Sluice Box seems to work fine for other people, judging by the lack of error reports, but whenever using it, on completion it will suddenly crash my server due to the tile entity ticking. Process I took is as follows:
1. Place Sluice Box.
2. Place Iron Rocky Chunk into Sluice.
3. Place Water into Sluice (was using Clay Bucket from Ceramics Mod)
4. Sluice functions as expected, until the working animation stops. No items are produced, and instead the server crashes moments later.
5. Restarting the server and logging back in near the Sluice Box will cause another instant crash of the same nature.
6. Use MCEdit to completely remove the Sluice Block and Tile Entity from the world.
7. Restart the server again. Place a new sluice, repeat test. Same result.

Warnings: I am using Optifine, Foamfix, and VanillaFix, although I did not see any of these come up in the crash report, nor do I think any of them would have caused a ticking tile entity.

Initial Crash: [crash-2018-08-30_00.45.22-server.txt](https://github.com/Magneticraft-Team/Magneticraft/files/2335332/crash-2018-08-30_00.45.22-server.txt)
Relog Crash: [crash-2018-08-30_00.52.27-server.txt](https://github.com/Magneticraft-Team/Magneticraft/files/2335333/crash-2018-08-30_00.52.27-server.txt)
Reproducing Test Crash: [crash-2018-08-30_01.20.00-server.txt](https://github.com/Magneticraft-Team/Magneticraft/files/2335334/crash-2018-08-30_01.20.00-server.txt)

**Comment by cout970** [comment]
oh, I see, for some reason the method to change the speed of and entity, only exist in the client. I can fix that really quick

**Comment by codewarrior0** [comment]
Seeing the same crash here. Would love to apply a server-side fix.
