### ISSUE TITLE
The recipe input stack cannot be empty!

### ISSUE THREAD

**Issue by InterruptingOctopus** [Magneticraft-Team/Magneticraft#135]
not sure whats causing this but all i know is that magneticraft returns the error featured in this crashlog
https://paste.dimdev.org/ewawitavix.mccrash

**Comment by cout970** [comment]
Weird, some mod seems to be changing the TRAPDOOR block, so when the recipe is registered that block doesn't exist

**Comment by cout970** [comment]
I guess I could ignore that recipe if the block is not found
