### ISSUE TITLE
Ore doubling not working with three and more ore stacks in crusher and sieve

### ISSUE THREAD

**Issue by duncanwebb** [Magneticraft-Team/Magneticraft#139]
Hi 
My set up shown in the attached image is working fine with one and two stacks of ore in the hopper above the grinder the output is two stacks and four stacks respectively.

However when I place three stacks in the hopper the output is four stacks and 48 ingots, 80 ingots too few. I can reproduce this and noticed after placing six and a half stacks of ore in the chest over the grinder and gone nine plus stacks back.

![magneticraft build](https://user-images.githubusercontent.com/4198031/45362496-454aed80-b5d5-11e8-9450-1ffd56007f49.png)

As the process takes a while to process I will have quit and restarted the game at least once from placing the ores in the hopper and them ending in the output chest. 

I placed an ingot on a conveyor belt and another in an inserter and they didn't de-spawn. I also removed the power from the sieve and placed and let the crusher feed it with a chunk and it didn't de-spawn.

Any ideas what is happening?

**Comment by cout970** [comment]
Thanks for the report, I'm not sure exactly what causes the issue, I will have to make tests and check the inventory saving system and the item processing system.

**Comment by cout970** [comment]
I'm closing this is there are no evidences that this bug still in the mod, feel free to reopen it if you detect any unusual result
