### ISSUE TITLE
Guide book

### ISSUE THREAD

**Issue by philip-iv** [Magneticraft-Team/Magneticraft#14]

**Comment by cout970** [comment]
I'm gona try to make the json serialization/deserialization

**Comment by cout970** [comment]
The serialization is done but there are some tasks that need to be finished, and I don't have time to do them, they are very small, so I'm sure someone will help with that

**Comment by jesmores** [comment]
fb6d19edb282d57b2f5d759bd0c22be0367d2742 is cout970's most recent commit for serialization w/ todo notes

**Comment by jesmores** [comment]
I'll see what I can do for the guidebook
