### ISSUE TITLE
Error: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics

### ISSUE THREAD

**Issue by paradoxmeem** [Magneticraft-Team/Magneticraft#149]
happens for no reason every time, im not sure if its because of the forge version or not but this error keeps popping up. everything is up to date,

**Comment by cout970** [comment]
Install https://minecraft.curseforge.com/projects/shadowfacts-forgelin?gameCategorySlug=mc-mods&projectID=248453

**Comment by cout970** [comment]
mmm, seems like the last version of forgelin is broken, just use the 1.8.0 version instead
