### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Sataana** [Magneticraft-Team/Magneticraft#150]
Trying to boot up a server.
It *appears* to be crashing on Magneticraft.

https://pastebin.com/g21HjfiT
[crash-2018-11-29_11.45.07-server.txt](https://github.com/Magneticraft-Team/Magneticraft/files/2629027/crash-2018-11-29_11.45.07-server.txt)

**Comment by inf1425** [comment]
It might be because you don't have modelloader:
https://minecraft.curseforge.com/projects/modelloader
