### ISSUE TITLE
Pumpjack Question

### ISSUE THREAD

**Issue by duncanwebb** [Magneticraft-Team/Magneticraft#151]
Does the pumpjack work in your last release? I've placed a pumpjack blueprint at 256, 300 and I reckon that this is a multiple of 2560 but the searching does not find anything. Am I doing this correctly.

Sorry to read that you are no longer maintaining the mod, it's fun and I like the animated engines and inserters, they're a great.

**Comment by cout970** [comment]
with multiple of 2560 I mean 0, 2560, 5120, 7680, etc. If you want to be sure if the oil is at that location you can dig a hole until you find oil "ores". You can also check the config file and modify the frequency of oil deposits

**Comment by duncanwebb** [comment]
Thanks, was I correct in assuming that x * z = 2560. I dug down at 10, 256 but didn't find any ores. I think Danny has not disabled them and I'll try at 0, 0 as its not that far away.
        oil {
            # If Oil source should be generated or not [default: true]
            B:active=true

            # Distance between oil deposits in multiples of 8
            I:distance=10

            # Probability of each block of oil to be generated
            D:probability=0.019999999552965164
        }

**Comment by duncanwebb** [comment]
Question 1, this this correct?
I think I've figured out the maths (been a while since I did geometry)
Ref https://en.wikipedia.org/wiki/Distance_from_a_point_to_a_line
x+z = 2560 (5120, etc)
ax + bz + c = 0 where a=1, b=1 and c=-2560
I'm at (m,n) so the nearest point is
x = ((m-n)+2560)/2, z = ((-m+n)+2560)/2

Question 2, does the pumpjack searches in columns starting from the blueprint and if so how far does it search?

Question 3, in the world generation of the book is doesn't say anything about oil ores, what are the min and max y?

Thanks

At 0,0 I dug down and found no oil ore blocks and the pumpjack didn't either. I've done a fair bit of mining and caving but so far haven't come across oil ore deposits.

I cheated a bit and placed some oil ores under the pumpjack and it shows, so I now know what happens if it finds oil.
![image](https://user-images.githubusercontent.com/4198031/49643513-35954680-fa16-11e8-9de0-d80234c9f3c5.png)

**Comment by cout970** [comment]
1. It's more simple than that, it's 2560 in x and 2560 in z, so valid coordinates are (0,0), (2560, 0), (2560, 2560), (0, 2560), etc.
2. Yes, it searches in 3x3 area all the way down until it finds an oil ore, and then starts scanning a bigger area at the same height as the oil ore.
3. oil deposits are always at Y 20 and can generate oil ores 3 blocks up or down, so min 17, max 23. the radius of the oil deposit is 5 chunks (with a round shape).

It's a bit weird that there is no deposit a 0,0

**Comment by duncanwebb** [comment]
Thank you very much, that's very clear and will help me find some ore. 

I did check quite carefully if there was ore at 0,0 and left the pumpjack there searching for a couple of minecraft days and also checked the configuration file for the initial version of the pack to make sure it was enabled then as 0,0 is very near world spawn and it I understand the process correctly ores are generated when the chunks are first created.

**Comment by duncanwebb** [comment]
This is what I see at 2560,-2560,20 no sign of oil
![image](https://user-images.githubusercontent.com/4198031/49688676-eafaf380-fb15-11e8-8a9f-a463b9e5728a.png)

Realtech pack has Immersive Petroleum and the oil from the ore is the Immersive Petroleum type and there are a few oil ponds about and I can refine the IP oil in the refinery.

Thanks again for your help and the mod.
