### ISSUE TITLE
Crash while launching the game

### ISSUE THREAD

**Issue by Kamefrede** [Magneticraft-Team/Magneticraft#153]
https://paste.dimdev.org/tehinuseyi.mccrash

Latest magneticraft, MTLib and modelloader

EDIT: Also running forge 2838

**Comment by cout970** [comment]
I will check it out tomorrow

**Comment by ghost** [comment]
The same happens to me when i try load my own modpack with magneticraft. 
(Everything is fine without it)
Running forge-14.23.5.2836 on minecraft 1.12.2

[crash-2019-06-17_15.22.56-client.txt](https://github.com/Magneticraft-Team/Magneticraft/files/3296887/crash-2019-06-17_15.22.56-client.txt)

**Comment by cout970** [comment]
Fixed in 2.6.1
