### ISSUE TITLE
Shelving Unit GUI out of alignment with inventory

### ISSUE THREAD

**Issue by Golrith** [Magneticraft-Team/Magneticraft#158]
Don't know if this is a JEI or MC issue, but after updating MC, the GUI doesn't align with the inventory.

![MCIssue](https://user-images.githubusercontent.com/41104391/60361400-fcceb600-99d5-11e9-83fd-b063713d790f.jpg)

Magneticraft_1.12-2.6.5-dev.jar
jei_1.12.2-4.15.0.283.jar

**Comment by cout970** [comment]
Fixed in 2.7.0
