### ISSUE TITLE
Some Rocky Chunks & Chunks have no smelting recipe

### ISSUE THREAD

**Issue by ghost** [Magneticraft-Team/Magneticraft#161]
* Copper Chunk
* Lead Chunk
* Cobalt Chunk
* Tungsten Chunk

--

* Copper Rocky Chunk
* Lead Rocky Chunk
* Cobalt Rocky Chunk
* Tungsten Rocky Chunk

**Comment by cout970** [comment]
They seem to work fine, if the error happens in the last version feel free to reopen this issue, maybe with more info (version of the mod, modpack, forge version)
