### ISSUE TITLE
[Suggestion] CT support for liquid fuels

### ISSUE THREAD

**Issue by wormzjl** [Magneticraft-Team/Magneticraft#162]
Hi, it's great to see the mod back into development again.
When testing the newly added large boiler + steam turbine, I wonder if we can have some customization method for liquid fuel values for it. Thanks!

**Comment by cout970** [comment]
Hi, the big combustion chamber uses the Buildcraft Fuel Manager for retrieving the fuel values, if Buildcraft is not present, an internal registry is used instead.
I haven't implemented support for CT, but if you have buildcraft installed you can any liquid fuel value.
For the steam boiler and steam turbine there are options in the config for speed.

**Comment by wormzjl** [comment]
Unfortunately I don't have bc in my pack :/

Cout970 <notifications@github.com> 于 2019年7月21日周日 03:08写道：
