### ISSUE TITLE
When aiming in any direction other than at a conveyor belt, the animation for the belt stops.

### ISSUE THREAD

**Issue by jusjudge** [Magneticraft-Team/Magneticraft#163]

**Comment by cout970** [comment]
Can you give me more info?
What is exactly the animation that stops? the items moving or the belt texture?
Can you send a gift/small video showing what happens?
What steps do I need to do to reproduce this bug?

**Comment by jusjudge** [comment]
When aiming at a wall or in any direction, this happens:
https://gph.is/g/Zynx6me

When I open my inventory, and look in the direction of the belts, they start to work:
https://gph.is/g/4gDrVJ9

Best way to reproduce it is simply by placing a conveyor or two down and having your crosshairs on the belt(s). They animation of them moving should work. Other than that, if you look anywhere else, it will stop. Items move along the belt fine though.

**Comment by cout970** [comment]
Ok, thank you for the detailed description and gifs, for some reason It works fine in my dev environment, I will perform more tests.

**Comment by cout970** [comment]
I'm unable to reproduce this bug, can you tell me which modpack are you using or the list of mods?
Are you using optifine? Are other animated blocks like water or prismarine working?

**Comment by Golrith** [comment]
I've noticed this issue in my Manufactio modpack. All other animated textures are fine.
I thought it was just a "feature" to help with performance as I'm sure early in my pack development these textures constantly animated.

**Comment by cout970** [comment]
This is caused by VanillaFix, you can disable "Texture optimisations" to fix the issue,
This has been explained in https://github.com/DimensionalDevelopment/VanillaFix/issues/199
