### ISSUE TITLE
Infinite energy with RF Transformer

### ISSUE THREAD

**Issue by leytilera** [Magneticraft-Team/Magneticraft#165]
When converting RF/FE with the RF Transformer to Magneticraft energy and then using electrical connectors to convert it back to RF/FE, you get infinite energy

**Comment by cout970** [comment]
oh, that's amazing, wait no, that terrible.
How much RF/t do you get?

**Comment by leytilera** [comment]
with 1 RF Transformer about 200 I think

**Comment by leytilera** [comment]
Ok, the roblem is not the RF Transformer, it is the electrical connector.

**Comment by cout970** [comment]
https://github.com/Magneticraft-Team/Magneticraft/commit/9b398cb2ef7c272ec2aac7395c1d7f0fdcb6efdd this commit fixes the bug
