### ISSUE TITLE
Making Double Plates

### ISSUE THREAD

**Issue by RechargeableAA** [Magneticraft-Team/Magneticraft#168]
I downloaded the mod about a day ago, so I'm sure it's the latest version. I also have Immersive Engineering installed if it's any correlation. So whenever I try to make double iron plates, it puts one damage on the hammer, (regardless of material) and gives me a single plate, but once it's damaged, it doesn't register the recipe. So I'm guessing the recipe doesn't register damage values.

tested on 8/21/19

**Comment by cout970** [comment]
I will take a look but probably I will just remove the recipe

**Comment by RechargeableAA** [comment]
Sounds good guys. I'm in love with the mod even in the beta stage. Keep up
the good work.
