### ISSUE TITLE
Inserter

### ISSUE THREAD

**Issue by jesmores** [Magneticraft-Team/Magneticraft#17]
Todo:
Animate robot arm
Make Delay between suckFromInv, putInInv and back again
Make GUI for inserting upgrades and whitelist/blacklist
Make whitelist/blacklist
Make react to redstone
Make Upgrades
Make interactions with other things than inventories (ground pickup/dropping, conveyor belt pickUp/dropping)

Consider making them able to pick up blocks (from Block state) and place Blocks (in block state)

**Comment by banpower1** [comment]
Added some todo points to create an overview
