### ISSUE TITLE
Documentation for CraftTweaker hydraulic press incorrect

### ISSUE THREAD

**Issue by topher2010** [Magneticraft-Team/Magneticraft#176]
On your Wiki, for the CraftTweaker information, the Hydraulic Press section is incorrect.

"# 4. mode: 0 -> Plates, 1 -> Light plates, 2 -> Heavy plates"

Should be:

"# 4. mode: 0 -> Light plates, 1 -> Medium plates, 2 -> Heavy plates"

**Comment by cout970** [comment]
oh, you are right, the name of the plates changed, but the names in the wiki are the same.
