### ISSUE TITLE
no way to get steel

### ISSUE THREAD

**Issue by ghost** [Magneticraft-Team/Magneticraft#179]
I just throw it in my ImmersiveEngineering-based minipack as it seems fit its steampunk style, but I couldn't find any way to get steel with Magneticraft. Last note was September last year about currently no support to make steel. Is this still true? May should be prioritized if so ...

**Comment by cout970** [comment]
yes, it's still true, there is no way to make steel in the mod, you can however add a custom recipe for steel.

I will not prioritize that because I'm very busy with other projects. The mod it's almost ported to 1.14/1.15 but I don't think it will be released soon™.

**Comment by ghost** [comment]
I'm playin in as an addition to a pack of only consist of IE + 2 or 3 IE-addons - and thought I could use your mod to get some steel early on without having to go to the nether for the blaze rods and try to hunt down slimes for the magma cream needed for their blast furnace - but as your mod doesn't have any way to make steel it's currently just the early game ore doubling ...
it has some potential and I love the in-world multiblock with overall factorio-based steampunk style ... really fits into IE ... I'm looking forward ... but I guess for now this can be closed ... thanks for the reply anyway
