### ISSUE TITLE
Fix Travis CI runs so they are useful

### ISSUE THREAD

**Issue by jesmores** [Magneticraft-Team/Magneticraft#20]
Currently broken coz of some weird JEI dependency stuff. See results below

https://travis-ci.org/Magneticraft-Team/Magneticraft/builds/163903457
https://travis-ci.org/Magneticraft-Team/Magneticraft/builds/163905730

and commits dde4cc3 and 07b7a42

**Comment by kylewill0725** [comment]
Fixed with #21 
Still need to update Readme with new build markdown.

**Comment by jesmores** [comment]
Thanks!
