### ISSUE TITLE
Inserters are inefficient in 'dropping' state

### ISSUE THREAD

**Issue by Baughn** [Magneticraft-Team/Magneticraft#3]
Although that's probably not the right terminology. Let me expand...

Inserters have basically two states:
- Blocked on waiting for the target inventory to empty out enough that some items can be moved
- Ditto, but with the arm at the target block, not at the source.

The latter can happen if, say, it tries to move 64 items into an inventory that only has room for 32. In this state, it uses its internal inventory as a buffer and continually checks if it can drop more items off.

I'm not sure of the details, or why this would be less efficient than the other state, but in any case it uses a lot more CPU time while doing this; to the point where a single inserter attempting to drop a stack into a JABBA barrel used 0.2ms of tick time on my server, as per Opis. Other inserters, in the 'blocked' state, did not.

**Comment by cout970** [comment]
This bug is in the 1.7.10 version (unsupported), in version 1.9 we rewrite all the mod from scratch, so this issue don't make sense here
