### ISSUE TITLE
Unable to disable oregen

### ISSUE THREAD

**Issue by JasonMcRay** [Magneticraft-Team/Magneticraft#48]
I am trying to disable World Generation of Copper (Chylcopyrite), Lead (Galena), Tungsten and Cobaltite from magneticraft. I have all set to false, but the ores are still generating.

Using:
MagneticCraft: 1.0.2 for Minecraft 1.10.2

**Comment by MechWarrior99** [comment]
We are aware of the issue and have fixed it. It will be out in the next update. Sorry for the inconvenience and delay :)

**Comment by LiaungYip** [comment]
In absence of a new release (for Minecraft 1.10.2 or otherwise), I'm working around this using the Custom Ore Generator mod to replace all Magneticraft ores with Stone.
