### ISSUE TITLE
Crushing Table should only auto-replace the thing you're hammering, not auto-place new ones from inventory

### ISSUE THREAD

**Issue by Barhandar** [Magneticraft-Team/Magneticraft#51]
If I'm hammering ores, I don't want it to decide my iron ingots are better as Magneticraft-exclusive plates and autoplace them there. Currently it searches inventory and places anything with valid output there. It should, instead, place nothing if the table is empty, place whatever you were hammering if it's found in inventory, and place nothing again if said thing was not found.

**Comment by MechWarrior99** [comment]
Hmm, that is a good point. Will look in to changing how it works. Thank you,
