### ISSUE TITLE
Is it possible to increase the ore processing multipliers via config?

### ISSUE THREAD

**Issue by clarabstract** [Magneticraft-Team/Magneticraft#61]
I don't see it exposed in the actual config, but I'm wondering if it can instead be accessed in the APIs available to things like crafttweaker ?

I'm trying to fit magneticraft together with rotarycraft and the 3x-ish multiplier stacks up kind of poorly considering how involved it is.

**Comment by cout970** [comment]
Last version has CraftTweaker support
