### ISSUE TITLE
1.12-2.0.2 conflict with Charcoal Pit 1.12-1.4_12

### ISSUE THREAD

**Issue by kreezxil** [Magneticraft-Team/Magneticraft#65]
Initially reported @ https://minecraft.curseforge.com/projects/charcoal-pit?comment=48

Issue: 1.12-1.4_12 crashes dedicated server Forge 1.12 build 2443

Notes:
on startup

crash report:
https://gist.github.com/d5798418eae8b6e5a0b34182a60e4d49

fml server latest:
https://gist.github.com/57065594ece030d8b5711e66429b9caa

Client part of the equation https://pastebin.com/EnYYpATz

----------------------

I updated and added the following to my Skyblock: Godless pack when the issue began, so I assume it is to do with one of these mods as prior to this the error did not exist.

Updated
Colossal Chests ::>ChangeLog
Cyclops Core ::>ChangeLog
Ender Utilities ::>ChangeLog
Industrial Foregoing ::>ChangeLog
Just Enough Items Jei ::>ChangeLog
Random Things ::>ChangeLog
Storage Drawers ::>ChangeLog
Added
Computality ::>ChangeLog
Rftools ::>ChangeLog
Rftools Control ::>ChangeLog
Et Lunar Environmental Tech Addon ::>ChangeLog
Environmental Tech ::>ChangeLog
Valkyrielib ::>ChangeLog
Magneticraft ::>ChangeLog
Modelloader ::>ChangeLog

------
Since my update was so small I started by removing mods on the server and restarting it, when I removed Magneticraft the issue the CharcoalPit went away.

**Comment by kreezxil** [comment]
I see you closed it but I don't see the resolution if any about it.

**Comment by cout970** [comment]
https://github.com/Magneticraft-Team/Magneticraft/commit/7c2d8b2d3ee2a1b396e763f1c9e444a4e39dfe27
The next update will have the fix, it will be out probably tomorrow

**Comment by kreezxil** [comment]
Cool, thanks.
