### ISSUE TITLE
[1.12.2][Suggestion] Use different Buckets on the Sluice Box

### ISSUE THREAD

**Issue by MasterEnderman** [Magneticraft-Team/Magneticraft#67]
The Sluice Box can be used as an early solution for resource gathering, but I'm having a problem, because at the current state in the modpack you won't be able to obtain an iron bucket. After some testing I realized that no other buckets from other mods works on the Slice Box. (tested with Ceramics an Clay Buckets)

Would it be possible to add support for those?

Forge: 14.23.0.2503
Magneticraft: 2.0.3

**Comment by davqvist** [comment]
yeah, having this issue as well, was just going to report that, accepting any fluid container with water in it, would be great.
