### ISSUE TITLE
[1.12] Magneticraft ore issue with Tinker's Construct Smeltery

### ISSUE THREAD

**Issue by ahWill** [Magneticraft-Team/Magneticraft#70]
Of the 5 ores this mod provides, 3 work because they are oreDictionaried as their end result. However I do not count Pyrite as an "ore" since it's only sulfur, no issue there. That being said, Galena Ore, is oreDictionaried as oreGalena (when end product is Lead), this is probably what's causing the issue with Tinker's Smeltery, the other 3 (Chalcopyrite -> oreCopper, Cobalite -> oreCobalt, Wolframite -> oreTungsten) work completely fine inside of Tinker's Smeltery.

**Comment by cout970** [comment]
Thats because Galena is not a lead ore, it's a compound of lead and silver. I will *eventually* add support for Tinker's Construct

**Comment by cout970** [comment]
I've been looking at the Tinkers' Construct api, and seems to be imposible to add a smeltery recipe that produces lead and silver. I tried adding a recipe to get only silver from galena, but it doesn't allow to add recipes for fluids already registed and silver is already registered for silver ore.

I don't know how to fix this so until someone come up with an idea, I will close this issue

**Comment by Divineaspect** [comment]
https://github.com/SkySom/MeltsAMany/blob/master/src/main/java/io/sommers/meltsamany/MeltRegistry.java

**Comment by cout970** [comment]
Seems plausible
