### ISSUE TITLE
Crushing table creates thermal expansion plates instead the mod ones

### ISSUE THREAD

**Issue by cout970** [Magneticraft-Team/Magneticraft#76]
Reminder for later:
https://github.com/Magneticraft-Team/Magneticraft/blob/1.12/src/main/kotlin/com/cout970/magneticraft/registry/Recipes.kt#L116
https://github.com/Magneticraft-Team/Magneticraft/blob/1.12/src/main/kotlin/com/cout970/magneticraft/item/EnumMetal.kt#L88
https://github.com/Magneticraft-Team/Magneticraft/blob/1.12/src/main/kotlin/com/cout970/magneticraft/registry/OreDictionary.kt#L29

**Comment by cout970** [comment]
This seems to be an issue with UniDict

**Comment by joselitosn** [comment]
Came here because of this bug, but even without UniDict, I still can't use oredict plates to build a Small Battery.

**Comment by cout970** [comment]
@joselitosn You can not use oredict plates because the magneticraft light plates are ment to be different from normal plates, the bug here is that UniDict ignores this and changes the plates for oreDict "equivalents" that are not really equivalent.
