### ISSUE TITLE
Question: Forgelin dependency

### ISSUE THREAD

**Issue by mainrs** [Magneticraft-Team/Magneticraft#78]
It looks like Magneticraft doesn't even use the Forgelin language adapter and instead uses the one within the base package. 
Am I overlooking something?

**Comment by cout970** [comment]
Yeah, I'm using forgelin just to not have to shade the kotlin stdlib myself. I did that for the 1.0.x versions of the mod (we are in the version 2.0.5), so that's why I have my own language adapter.

**Comment by mainrs** [comment]
Ah thank you for answering the question :smile:
