### ISSUE TITLE
missing cobalt oregen config

### ISSUE THREAD

**Issue by dancc7t** [Magneticraft-Team/Magneticraft#79]
Hello, i am making a new modpack, which relies on a custom oregen based on biome type, but cobaltite is not included in the config file like the rest of ores, so i cannot disable it and thus it appears in every biome (i want it to spawn only in some dry biomes like savanna), could you please include it in the next version?

Thanks

**Comment by cout970** [comment]
what do you mean with `i cannot disable it`?  it's disable by default and there is no way to enable it.
In fact there is no code to generate cobaltite in the last version: 
https://github.com/Magneticraft-Team/Magneticraft/blob/1.12/src/main/kotlin/com/cout970/magneticraft/world/WorldGenerator.kt#L19

**Comment by dancc7t** [comment]
i have generated it using cofhworld worldgen, it is indeed not generated inside that function, so that means it only spawns on the biomes i whitelisted, which is alright. But i wonder why it got disabled, cobalt is not like copper which is added by +50 other mods, it is an uncommon material i want to use as base for many recipes of my WIP modpack.

Thanks for the info cout970.

**Comment by cout970** [comment]
Cobalt is disabled for balancing issues, basically Tinkers construct cobalt is a high tier material, and we want a low-mid tier material for batteries
