### ISSUE TITLE
Light Plates not following Oredict entries, No crafting method for any plates Light or Heavy

### ISSUE THREAD

**Issue by Gunner76th** [Magneticraft-Team/Magneticraft#84]
![image](https://user-images.githubusercontent.com/5566872/37254960-0a222790-251c-11e8-9da6-fa24494a6dbb.png)

In the modpack Beyond the Void, the Light and Heavy plates have no crafting recipe, and I have already checked and confirmed that the recipes are not being removed or altered by minetweaker/crafttweaker. 

In addition, the Light Plates register as an oredict for normal plates from mods such as Thermal Expansion, however the crafting recipes do not currently show support for oredict usage. As such, virtually everything that requires a plate must be "cheated" in using creative mode, or all of the recipes must be manually altered using MT/CT. 

Attached is an example of the expanded details for the Light Iron Plate.

**Comment by Gunner76th** [comment]
Here is the extended information from the Iron Plate that can be crafted in the modpack, and that matches the Oredict entry for the Light Iron Plate

![image](https://user-images.githubusercontent.com/5566872/37255055-21b2817e-251d-11e8-9f6e-19ebcc87ec72.png)

**Comment by Gunner76th** [comment]
Also, just to clarify, this applies to ALL magneticraft plates of all material types, both Heavy and Light.

**Comment by cout970** [comment]
Light plates from magneticraft and plates from other mods are ment to be different, the oreDictionary tag is temporary, so they can be used to craft stuff in other mods while the hydraulic press is not finished. To make light plates you need to use a crushing table, if the recipe is missing or changed then other mod is breaking stuff, probably UniDict, you can disable the integration in their config. Heavy plates have no recipe yet, and they are not used in any crafting recipe
