### ISSUE TITLE
Cannot take items out of shelves after searching

### ISSUE THREAD

**Issue by pagameba** [Magneticraft-Team/Magneticraft#85]
Hi, I'm playing Modern Skyblock 3/Departed on a server, latest version 3.1.5.3 which includes Magneticraft 1.12.2-2.1.2.jar.  I'm using the shelving unit full stocked with chests.  The problem I'm having is if I search for something using the search input, then take out items (either shift-click or click and drag), the items appear in my inventory and are removed from the shelving unit until I exit the UI.  Then when I try to interact with the stack of items, all stacks that I removed disappear and are back in the shelving unit.  If it matters, its stacks of chickens that I'm searching on.

**Comment by cout970** [comment]
I tried to reproduce but i didn't succeed, Seems to be just a desync, so maybe the server is not receiving the search string or the language of the server and the client differs.

**Comment by pagameba** [comment]
A bit more detail on this, it was happening with chickens from the Roost mod. I just tried again with other items from vanilla and other mods and it seems to be working (can remove items with an active search).   I just did another test and it is definitely not working with the chickens when there is a search term in the search box.  Weird!  It also affects inserting chickens while there is an active search, not sure if that detail helps or not.

**Comment by cout970** [comment]
Thanks for the info, I will investigate the mod, I'm pretty sure that there is just a desync caused by applying the filter in the client and the server, something may be different, maybe a config file or a language file, I will change that so the filter only works on the server and send the result to the client.
