### ISSUE TITLE
Shelving Unit reports double the amount of items to other mods.

### ISSUE THREAD

**Issue by calloatti** [Magneticraft-Team/Magneticraft#88]
MC 1.12.2
Magneticraft_1.12-2.1.2

Shelving Unit reports double the amount of items to The One Probe and Refined Storage.

![image](https://user-images.githubusercontent.com/12817862/37812954-b0931962-2e41-11e8-9ea5-a97254eb6019.png)

![image](https://user-images.githubusercontent.com/12817862/37812961-c7ff2bfe-2e41-11e8-8d5d-9ace16c9c8fe.png)

Shelving Unit connect to a Refined Storage system using 3 external storage connectors and cable:

![image](https://user-images.githubusercontent.com/12817862/37812984-e2e38712-2e41-11e8-8734-0db77f24326f.png)

When extracting the items from the Refined Storage grid, only 4 come out of course.

**Comment by cout970** [comment]
This needs more investigation, I will skip it for the release 2.2.0
