### ISSUE TITLE
buckets disappears after trying to get the liquid from the copper tank

### ISSUE THREAD

**Issue by ghost** [Magneticraft-Team/Magneticraft#92]
title says it all. The buckets, should more than 2 be stacked at once, disappear when taking liquid starlight out of the copper tank. only a bucket with the starlight remains. the others disappear.

edit: its not only starlight. this affects all liquids. if you try to take them out with several buckets, the buckets will disappear.

here's another video:

https://files.ilikepudding.tk/l9nsbbnjy9.mp4

Minecraft: 1.12.2
Magneticraft: Magneticraft_1.12-2.1.2
Modelloader: modelloader-1.0.5
Forgelin: Forgelin-1.6.0
Modpack: Crimson Skies

**Comment by cout970** [comment]
Sorry but I was unable to reproduce the issue, try to update to the version Magneticraft_1.12-2.2.1 and see if it still happens.

**Comment by ghost** [comment]
ok with the update it now seems to work. Thank you
