### ISSUE TITLE
Excessive Cascading Chunk Loads

### ISSUE THREAD

**Issue by FriendlyGamer** [Magneticraft-Team/Magneticraft#96]
When I am in a mining world (ID 6 from Aroma's Dimensional mod or whatever it called) my console is being spammed by your mod... 
12.04 12:17:23 [Server] Server thread/WARN [FML]: Magneticraft loaded a new chunk [5, 9] in dimension 6 (MiningWorld) while populating chunk [6, 10], causing cascading worldgen lag. 

It keep on doing this over, over, and over again.  

Thanks in advance!

**Comment by cout970** [comment]
Thanks for the report, fixed in 091ef4f72ec87daa904b4f985347e541d9712dfe
