### ISSUE TITLE
[Suggestion] pwd and clear commands for Shell

### ISSUE THREAD

**Issue by Lykrast** [Magneticraft-Team/Magneticraft#99]
Having the bash/shell commands `pwd` and `clear` would be an helpful quality of life improvement to the Shell floppy disk.

`pwd` prints the current directory, while `clear` clears all text from the terminal (or spams empty lines until the terminal is clear, I honestly don't know).

**Comment by cout970** [comment]
Will add them eventually. They are really easy to implement (there is a clear function but not clear command) but I can't work on that until the weekend.
btw there is a repo for the computer programs [here](https://github.com/Magneticraft-Team/Computer)
